:favicon:
:doctype: book

include::./SA_vars.adoc[]

= {title}
////

Authors
Peter Schinagl, SUSE Solution GmbH, peters@suse.com
Stephen Mogg, SUSE Solutions, Stephen.Mogg@suse.com
Abdelrahman Mohamed, SUSE Solutions GmbH, abdelrahman.mohamed@suse.com
Bryan Gartner, SUSE Solutions, bryan.gartner@suse.com

////

== Preface

This reference document contains best practices and planning considerations when using SUSE's Automation templates for SAP Landscapes.

It is targeted at consultants and end-customers deploying SAP Landscapes in the public cloud and provides guidance on how Terraform, SALT, and other components work together to provide a consistent and validated architecture.

The document can also be used as a guide for a partner enablement workshop covering the proper use of these tools.

The following, layered footnote:Archimate[link: https://pubs.opengroup.org/architecture/archimate3-doc[Archimate Enterprise Architecture]] aspects will be covered:

ifdef::Strategy[]
* *_Why_* one should consider this strategy
endif::Strategy[]
ifdef::Business[]
* *_Who_* to engage with, inform and collaborate with
* *_What_* key factors are important and *_When_* to consider them
endif::Business[]
ifdef::Application[]
* *_What_* software and applications this is relevant to accomplish
endif::Application[]
ifdef::Technology[]
* *_How_* various technology components can facilitate this
endif::Technology[]
ifdef::Physical[]
* *_Where_* the resulting solution may physically or virtually reside
endif::Physical[]

// Introduction
include::./i-Introduction/SA.adoc[]

// Strategy
ifdef::Strategy[]
include::./ii-Strategy/SA.adoc[]
endif::Strategy[]

// Business
ifdef::Business[]
include::./iii-Business/SA.adoc[]
endif::Business[]

// Application
ifdef::Application[]
include::./iv-Application/SA.adoc[]
endif::Application[]

// Technology
ifdef::Technology[]
include::./v-Technology/SA.adoc[]
endif::Technology[]

// Physical
ifdef::Physical[]
include::./vi-Physical/SA.adoc[]
endif::Physical[]

// Migration
ifdef::Migration[]
include::./vii-Migration/SA.adoc[]
endif::Migration[]

== Summary

More and more companies move to a computing _as a service_, rather than _as a product_, which bring new possibilities for innovations, but reshaping the landscape, will bring new challenges where SUSE can help with to solve them.

The SUSE solution manages complex operations with automation and help ease the transition to Linux and the cloud, and reduce the problem resolution time with insights to the SAP infrastructure landscape.

It help to deliver SAP services faster, more efficiently and with less risk.


ifdef::Glossary[]
include::./SA-Glossary.adoc[]
endif::Glossary[]

ifdef::Appendix[]
include::./SA-Appendix.adoc[]
endif::Appendix[]

